### ISSUE TITLE
Replace broken jira links with working github links

### ISSUE THREAD

**Issue by neoneye** [RockfordWei/Perfect-Issues#1]
I like to contribute to this project, but I'm confused about how. The jira website is not responding. What is the "right way" to create an issue?

Perhaps replace jira links with these new github links?

As of 6may2018 there are many dead links to jira.

The new issue tracker is here:
https://github.com/PerfectlySoft/Perfect-Issues/
https://github.com/PerfectlySoft/Perfect-Assistant-Issues

# Website

The perfect.org website refer to Jira link at the bottom of the page:
https://www.perfect.org/
https://www.perfect.org/feature-requests.html
https://www.perfect.org/support.html

# Repos

There are some repos that still refer to jira:
https://github.com/PerfectServers/AuthenticationServer
https://github.com/PerfectServers/Perfect-LogServer
https://github.com/PerfectServers/Perfect-Markdown-Editor
https://github.com/PerfectServers/SwiftSlack
https://github.com/PerfectExamples/Perfect-Authentication-Demo
https://github.com/PerfectExamples/Perfect-Session-PostgreSQL-Demo
https://github.com/PerfectExamples/Perfect-Blog-Mustache
https://github.com/PerfectExamples/Perfect-Weather
https://github.com/PerfectExamples/ImageLibraryDemo

# Repo: Perfect-Issues

https://github.com/PerfectlySoft/Perfect-Issues

Its title is currently "JIRA Archive of Perfect.", which sounds like it's an old snapshot. Perhaps change to "The official issue tracker for Perfect".

There are possible more places that refer to jira.

**Comment by kjessup** [comment]
Thank you. I've removed Jira mention from the web site itself. I clarified the purpose of the "Perfect-Issues" repository and renamed it. I've edited the READMEs you pointed out which still mention Jira.

For new issues & requests, please open a GitHub issue in the relevant repository.
If it is a Perfect Assistant related issue, you correctly pointed out that it now has its own repository specifically for tracking issues.

Thanks!
